---
title: "bias_data_analysis"
author: "Lindsey Greenhill"
date: "11/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gt)
library(quanteda)
library(broom)
library(skimr)
library(lubridate)
library(janitor)
library(dotwhisker)
library(tidytext)
library(haven)
library(ggthemes)
library(webshot)
library(stargazer)
library(tidyverse)
library(patchwork)
library(ggrepel)
library(ggpubr)
load("data/bias_data/bias_data_clean.RData")
```

# Dictionary

```{r echo=FALSE}

# dictionary taken from analysis for Gov1372

content_dict <- dictionary(list(republican = c("biden",
                                               "border",
                                               "democrat",
                                               "spend",
                                               "illeg",
                                               "china",
                                               "inflat",
                                               "pelosi",
                                               "trillion",
                                               "afghanistan",
                                               "polici",
                                               "southern",
                                               "communist",
                                          "bidenbordercrisi",
                                          "radic",
                                          "mandat",
                                          "joe",
                                          "dem",
                                          "taxpay",
                                          "socialist"),
                                democrat = c("black",
                                             "work",
                                             "payment",
                                             "violenc",
                                             "vote",
                                             "act",
                                             "childtaxcredit",
                                             "pandem",
                                             "democraci",
                                             "communiti",
                                             "famili",
                                             "child",
                                             "help",
                                             "buildbackbett",
                                             "pass",
                                             "care",
                                             "invest",
                                             "climat",
                                        "americanrescueplan",
                                        "health")))
```

## Text Corpus

```{r echo=FALSE}

# creating text corpus

text_corpus <- corpus(tidy_data, text_field = "text")

# creating dfm for cocntent analysis

content_toks <- tokens(text_corpus,
               remove_punct = TRUE,
               remove_symbols = TRUE,
               remove_numbers = TRUE,
               remove_url = TRUE) %>%
  tokens_tolower() %>%
  tokens_remove(pattern=stopwords("en")) %>%
  tokens_remove(pattern = c("u201c", "u00b0", "u2014", "wopi", "avi", "ooo", 
                            "000", "ito", "ynl", "f'avl", "foxnews.com", 
                            "ufb02pi", "ufb021", "ufbo2l", "ufb02L", "rpm")) %>%
  tokens_select(min_nchar = 3)

content_dfm <- dfm(content_toks, groups = c("channel", "date"))

# selecting words in the dictionaries

content_categories <- dfm_lookup(content_dfm, dictionary = content_dict)

# turning dfm into dataframe

content_df <- convert(content_categories, to = "data.frame") %>%
  group_by(doc_id) %>%
  separate(doc_id, c("channel", "date"), extra = "merge") %>%
  mutate(date = ymd(date))

```

## Boxplots

```{r echo=FALSE}

# creating boxplots of word counts

rep_box_count <- content_df %>%
  group_by(channel) %>%
  ggplot(., aes(channel, republican)) +
  geom_boxplot() +
  theme_clean() +
  labs(title = "Republican Language in Chyrons by Channel",
       x = "Channel",
       y = "Daily Language Count")

dem_box_count <- content_df %>%
  group_by(channel) %>%
  ggplot(., aes(channel, democrat)) +
  geom_boxplot() +
  theme_clean() +
  labs(title = "Democrat Language in Chyrons by Channel",
       x = "Channel",
       y = "Daily Language Count")

rep_box_count
dem_box_count

# now I'm creating a "score" variable that is Republican language - Democrat
# language

content_df <- content_df %>%
  mutate(score = republican - democrat,
         channel = as_factor(channel))

score_box <- content_df %>%
  group_by(channel) %>%
  ggplot(., aes(channel, score)) +
  geom_boxplot() +
  theme_clean() +
  labs(title = "Language Score by Channel",
       subtitle = "Score = Republican - Democrat",
       x = "Channel",
       y = "Daily Language Score")
score_box
  
```

##  Regression

```{r echo=FALSE, results = "asis", message=FALSE}

# doing scatterplots

rep_scatter <- content_df %>%
  ggplot(aes(x = date, y = republican, color = channel, fill = channel)) +
  geom_smooth(method = "lm") +
  geom_point() +
  theme_clean() +
  labs(title = "Republican Language by Channel",
       x = "Date",
       y = "Daily Language Count")

dem_scatter <- content_df %>%
  ggplot(aes(x = date, y = democrat, color = channel, fill = channel)) +
  geom_smooth(method = "lm") +
  geom_point() +
  theme_clean() +
  labs(title = "Democrat Language by Channel",
       x = "Date",
       y = "Daily Language Count")

score_scatter <- content_df %>%
  ggplot(aes(x = date, y = score, color = channel, fill = channel)) +
  geom_smooth(method = "lm") +
  geom_point() +
  theme_clean() +
  labs(title = "Language Score by Channel",
       x = "Date",
       y = "Daily Language Count")

rep_scatter
dem_scatter
score_scatter

# no dates

mod_rep <- lm(republican ~ channel,
              data = content_df)
mod_dem <- lm(democrat ~ channel,
              data = content_df)
mod_score <- lm(score ~ channel ,
                data = content_df)

stargazer(mod_rep,
          mod_dem,
          mod_score,
          type = "latex")

```

