---
title: "data_analysis"
author: "Lindsey Greenhill"
date: "10/11/2021"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Loading necessary packages
library(gt)
library(quanteda)
library(broom)
library(skimr)
library(lubridate)
library(janitor)
library(dotwhisker)
library(tidytext)
library(haven)
library(ggthemes)
library(webshot)
library(stargazer)
library(tidyverse)
library(patchwork)
library(ggrepel)
library(ggpubr)
```

```{r data loading, message = FALSE, include = FALSE}

tidy_chyrons <- read_csv("tidy_chyron_data.csv")

# Turning data into a corpus for quanteda

text_corpus <- corpus(tidy_chyrons, text_field = "text")
  
```


## Wordclouds

```{r tokens_2, echo=FALSE}

# turning corpus into tokens. Removing unimportant words and selectng for ngrams
# = 2. Code taken from gov51 final project

toks_2 <- tokens(text_corpus,
               remove_punct = TRUE,
               remove_symbols = TRUE,
               remove_numbers = TRUE,
               remove_url = TRUE) %>%
  tokens_tolower() %>%
  tokens_remove(pattern=stopwords("en")) %>%
  tokens_remove(pattern = c("u201c", "u00b0", "u2014", "wopi", "avi", "ooo", 
                            "000", "ito", "ynl", "f'avl", "foxnews.com", 
                            "ufb02pi", "ufb021", "ufbo2l", "ufb02L", "rpm")) %>%
  tokens_select(min_nchar = 3) %>%
  tokens_ngrams(n = 2)

```

### Two word phrases
```{r wordcloud_2, echo=FALSE}

# thing to talk about -- Mueller report
wordcloud_dfm_2 <- dfm(toks_2, groups = "channel")
textplot_wordcloud(wordcloud_dfm_2, comparison = T,
                   min_count = 200,
                   min_size = .5,
                   max_size = 3.7)

```



```{r tokens_3, echo=FALSE}

# turning corpus into tokens. Removing unimportant words and selectng for ngrams
# = 2. Code taken from gov51 final project

toks_3 <- tokens(text_corpus,
               remove_punct = TRUE,
               remove_symbols = TRUE,
               remove_numbers = TRUE,
               remove_url = TRUE) %>%
  tokens_tolower() %>%
  tokens_remove(pattern=stopwords("en")) %>%
  tokens_remove(pattern = c("u201c", "u00b0", "u2014", "wopi", "avi", "ooo", 
                            "000", "ito", "ynl", "f'avl", "foxnews.com", 
                            "ufb02pi", "ufb021", "ufbo2l", "ufb02L", "rpm")) %>%
  tokens_select(min_nchar = 3) %>%
  tokens_ngrams(n = 3)

```

### Three word phrases

```{r wordcloud_3, echo=FALSE}

# thing to talk about -- Mueller report
wordcloud_dfm_3 <- dfm(toks_3, groups = "channel")
textplot_wordcloud(wordcloud_dfm_3, comparison = T,
                   min_count = 200,
                   min_size = .5,
                   max_size = 3.7)

```
