---
title: "sentiment_data_analysis"
author: "Lindsey Greenhill"
date: "11/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gt)
library(quanteda)
library(broom)
library(skimr)
library(lubridate)
library(janitor)
library(dotwhisker)
library(textdata)
library(tidytext)
library(haven)
library(ggthemes)
library(webshot)
library(stargazer)
library(tidyverse)
library(patchwork)
library(tidytext)
library(ggrepel)
library(ggpubr)
load("data/bias_data/bias_data_clean.RData")
```

## Afghanistan

```{r echo=FALSE}

# creating an afghanistan DF

afghanistan_df <- tidy_data %>%
  mutate(text = tolower(text),
         mention = grepl("afghanistan", text)) %>%
  filter(mention)

# creating a chyron ID

afghanistan_df$chyron_id <- seq.int(nrow(afghanistan_df))

# looking at the daily counts

afghanistan_chyron_counts <- tidy_data %>%
  mutate(text = tolower(text),
         mention = grepl("afghanistan", text)) %>%
  filter(mention) %>%
  count(date, channel) %>%
  ggplot(aes(x = date, y = n)) +
  geom_col() +
  facet_wrap(~channel) +
  theme_clean() +
  labs(title = "Chyrons that mention Afghanistan",
       x = "",
       y = "# Chyrons")

afghanistan_chyron_counts

# ggsave(plot = afghanistan_chyron_counts, "plots/afghanistan_chyron_counts.png")

# doing the sentiment analysis

af_sentiment <- afghanistan_df %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("afinn"))

sentiment_scores <- afghanistan_df %>%
  left_join(af_sentiment %>%
              group_by(chyron_id) %>%
              summarise(score = sum(value))) %>%
  replace_na(list(score = 0))

# going to do a scatterplot and boxplot

af_scatter_plot <- sentiment_scores %>%
  ggplot(aes(x = date, y = score)) +
  geom_point(color = "azure3") +
  facet_wrap(~channel) +
  theme_clean()  +
  labs(title = "Sentiment Scores of Chyrons mentioning Afghanistan",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = af_scatter_plot, "plots/af_sentiment_scatter_plot.png")

af_box_plot <- sentiment_scores %>%
  ggplot(aes(x = channel, y = score)) +
  geom_boxplot(fill = "azure3") +
  theme_clean() +
  labs(title = "Sentiment Scores of Chyrons mentioning Afghanistan",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = af_box_plot, "plots/af_sentiment_boxplot.png")

af_scatter_plot
af_box_plot
```

## Covid

```{r echo=FALSE}

# saying either covid or corona counts

covid_df <- tidy_data %>%
  mutate(text = tolower(text),
         mention_covid = grepl("covid", text),
         mention_corona = grepl("corona", text),
         mention = if_else(mention_covid | mention_corona, TRUE, FALSE)) %>%
  filter(mention)

covid_df$chyron_id <- seq.int(nrow(covid_df))

covid_chyron_counts <- covid_df %>%
  count(date, channel) %>%
  ggplot(aes(x = date, y = n)) +
  geom_col() +
  facet_wrap(~channel) +
  theme_clean() +
  labs(title = "Chyrons that mention Covid",
       x = "",
       y = "# Chyrons")

covid_chyron_counts

# ggsave(plot = covid_chyron_counts, "plots/covid_chyron_counts.png")

# doing the sentiment analysis

covid_sentiment <- covid_df %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("afinn"))

sentiment_scores_covid <- covid_df %>%
  left_join(covid_sentiment %>%
              group_by(chyron_id) %>%
              summarise(score = sum(value))) %>%
  replace_na(list(score = 0))

# going to do a scatterplot and boxplot

covid_scatter_plot <- sentiment_scores_covid %>%
  ggplot(aes(x = date, y = score)) +
  geom_point(color = "azure3") +
  facet_wrap(~channel) +
  theme_clean()  +
  labs(title = "Sentiment Scores of Chyrons mentioning Covid",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = covid_scatter_plot, "plots/covid_sentiment_scatter_plot.png")

covid_box_plot <- sentiment_scores_covid %>%
  ggplot(aes(x = channel, y = score)) +
  geom_boxplot(fill = "azure3") +
  theme_clean() +
  labs(title = "Sentiment Scores of Chyrons mentioning Covid",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = covid_box_plot, "plots/covid_sentiment_boxplot.png")

covid_scatter_plot
covid_box_plot
```

## Impeachment

```{r echo=FALSE}
impeach_df <- tidy_data %>%
  mutate(text = tolower(text),
         mention = grepl("impeach", text)) %>%
  filter(mention)

impeach_df$chyron_id <- seq.int(nrow(impeach_df))

impeach_chyron_counts <- impeach_df %>%
  count(date, channel) %>%
  ggplot(aes(x = date, y = n)) +
  geom_col() +
  facet_wrap(~channel) +
  theme_clean() +
  labs(title = "Chyrons that mention Impeachment",
       x = "",
       y = "# Chyrons")

impeach_chyron_counts

# ggsave(plot = impeach_chyron_counts, "plots/impeach_chyron_counts.png")

# doing the sentiment analysis

impeach_sentiment <- impeach_df %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("afinn"))

sentiment_scores_impeach <- impeach_df %>%
  left_join(impeach_sentiment %>%
              group_by(chyron_id) %>%
              summarise(score = sum(value))) %>%
  replace_na(list(score = 0))

# going to do a scatterplot and boxplot

impeach_scatter_plot <- sentiment_scores_impeach %>%
  ggplot(aes(x = date, y = score)) +
  geom_point(color = "azure3") +
  facet_wrap(~channel) +
  theme_clean()  +
  labs(title = "Sentiment Scores of Chyrons mentioning Impeachment",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = impeach_scatter_plot, "plots/impeach_sentiment_scatter_plot.png")

impeach_box_plot <- sentiment_scores_impeach %>%
  ggplot(aes(x = channel, y = score)) +
  geom_boxplot(fill = "azure3") +
  theme_clean() +
  labs(title = "Sentiment Scores of Chyrons mentioning Impeachment",
       x = "",
       y = "Sentiment Score")

# ggsave(plot = impeach_box_plot, "plots/impeach_sentiment_boxplot.png")

impeach_scatter_plot
impeach_box_plot


```


